// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi2pySTrY2wfepQ0ke4opkjlhctn2gvMk',
    appId: '1:818472542164:web:18394e90a0722f14ff4041',
    messagingSenderId: '818472542164',
    projectId: 'quanlyhocvu-f5867',
    authDomain: 'quanlyhocvu-f5867.firebaseapp.com',
    storageBucket: 'quanlyhocvu-f5867.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWFRPz6tArHu0FnzKrkz_JlE5u5GmHeyE',
    appId: '1:818472542164:android:78b451a2d9ec1a9eff4041',
    messagingSenderId: '818472542164',
    projectId: 'quanlyhocvu-f5867',
    storageBucket: 'quanlyhocvu-f5867.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOUab6k3fsFUEE3P-h2dLhx1qKF0sjlMY',
    appId: '1:818472542164:ios:923d9f1268463cebff4041',
    messagingSenderId: '818472542164',
    projectId: 'quanlyhocvu-f5867',
    storageBucket: 'quanlyhocvu-f5867.firebasestorage.app',
    iosBundleId: 'com.example.studentSchedule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOUab6k3fsFUEE3P-h2dLhx1qKF0sjlMY',
    appId: '1:818472542164:ios:923d9f1268463cebff4041',
    messagingSenderId: '818472542164',
    projectId: 'quanlyhocvu-f5867',
    storageBucket: 'quanlyhocvu-f5867.firebasestorage.app',
    iosBundleId: 'com.example.studentSchedule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi2pySTrY2wfepQ0ke4opkjlhctn2gvMk',
    appId: '1:818472542164:web:9798b1b06214c11cff4041',
    messagingSenderId: '818472542164',
    projectId: 'quanlyhocvu-f5867',
    authDomain: 'quanlyhocvu-f5867.firebaseapp.com',
    storageBucket: 'quanlyhocvu-f5867.firebasestorage.app',
  );
}
